-- ============================================================
-- Project 6: Employee Engagement Segmentation Dashboard
-- SQL Queries — Engagement Audit and Segmentation Analysis
--
-- Research foundation:
--   Gallup Q12 Employee Engagement Survey
--     12 items rated 1-5 measuring psychological conditions
--     employees need to be engaged.
--
--   Gallup State of the Global Workplace Report (2023)
--     23% engaged globally, 59% not engaged, 18% actively disengaged.
--     Manager quality accounts for 70% of team engagement variance.
--     Engaged employees show 81% lower absenteeism and 23% higher profitability.
--     Cost of global disengagement: $8.8 trillion (9% of GDP).
--
-- Compatible with: PostgreSQL 13+
-- Source table:    engagement_data
-- Generated by:    engagement_generator.py
-- ============================================================


-- ============================================================
-- QUERY 1: ENGAGEMENT SEGMENTATION OVERVIEW
-- Headline numbers for the executive summary page.
-- Gallup 2023 benchmarks: Engaged 23%, Not Engaged 59%, Actively Disengaged 18%.
-- ============================================================

SELECT
    engagement_segment,
    COUNT(*)                                                        AS headcount,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 1)             AS pct_of_workforce,
    ROUND(AVG(avg_q12_score), 3)                                    AS avg_q12_score,
    ROUND(AVG(absence_days), 1)                                     AS avg_absence_days,
    ROUND(AVG(performance_rating), 2)                               AS avg_performance_rating,
    ROUND(AVG(intent_to_stay), 2)                                   AS avg_intent_to_stay,
    SUM(flight_risk_flag)                                           AS flight_risk_count
FROM engagement_data
GROUP BY engagement_segment
ORDER BY avg_q12_score DESC;


-- ============================================================
-- QUERY 2: SEGMENT DISTRIBUTION BY DEPARTMENT
-- Identifies which departments have the lowest engagement.
-- Operations and Customer Support expected to rank lowest based on
-- Gallup data showing frontline and service roles are hardest to engage.
-- ============================================================

SELECT
    department,
    engagement_segment,
    COUNT(*)                                                        AS headcount,
    ROUND(
        COUNT(*) * 100.0
        / SUM(COUNT(*)) OVER (PARTITION BY department),
        1
    )                                                               AS pct_within_dept
FROM engagement_data
GROUP BY department, engagement_segment
ORDER BY department, avg_q12_score DESC;


-- ============================================================
-- QUERY 3: Q12 ITEM-LEVEL AVERAGES BY DEPARTMENT
-- Reveals which engagement dimensions are weakest in each department.
-- Manager-heavy items (Q04, Q05, Q06, Q07, Q11) signal leadership issues.
-- Environment items (Q01, Q02, Q03) signal structural or resource issues.
-- ============================================================

SELECT
    department,
    ROUND(AVG(q01), 3) AS q01_expectations,
    ROUND(AVG(q02), 3) AS q02_materials,
    ROUND(AVG(q03), 3) AS q03_do_best,
    ROUND(AVG(q04), 3) AS q04_recognition,
    ROUND(AVG(q05), 3) AS q05_cares_about_me,
    ROUND(AVG(q06), 3) AS q06_development,
    ROUND(AVG(q07), 3) AS q07_opinions_count,
    ROUND(AVG(q08), 3) AS q08_mission,
    ROUND(AVG(q09), 3) AS q09_quality_commitment,
    ROUND(AVG(q10), 3) AS q10_best_friend,
    ROUND(AVG(q11), 3) AS q11_progress_conversation,
    ROUND(AVG(q12), 3) AS q12_learn_and_grow,
    ROUND(AVG(avg_q12_score), 3) AS overall_avg
FROM engagement_data
GROUP BY department
ORDER BY overall_avg ASC;


-- ============================================================
-- QUERY 4: MANAGER-LEVEL ENGAGEMENT RANKING
-- Gallup: manager quality explains ~70% of team engagement variance.
-- Managers with avg team score below 2.80 are primary intervention targets.
-- ============================================================

SELECT
    manager_id,
    department,
    COUNT(*)                                    AS team_size,
    ROUND(AVG(avg_q12_score), 3)                AS team_avg_q12,
    ROUND(AVG(manager_quality), 4)              AS manager_quality_score,
    ROUND(AVG(absence_days), 1)                 AS team_avg_absence_days,
    SUM(flight_risk_flag)                       AS flight_risk_count,
    ROUND(
        SUM(flight_risk_flag) * 100.0
        / COUNT(*),
        1
    )                                           AS flight_risk_pct,
    SUM(CASE WHEN engagement_segment = 'Engaged'              THEN 1 ELSE 0 END) AS engaged_count,
    SUM(CASE WHEN engagement_segment = 'Actively Disengaged'  THEN 1 ELSE 0 END) AS disengaged_count
FROM engagement_data
GROUP BY manager_id, department
HAVING COUNT(*) >= 3
ORDER BY team_avg_q12 ASC;


-- ============================================================
-- QUERY 5: ENGAGEMENT BY TENURE BAND
-- Gallup documents a honeymoon effect for new hires (< 6 months)
-- and a bimodal distribution at long tenure (> 10 years):
-- employees are either deeply committed or checked out.
-- ============================================================

WITH tenure_bands AS (
    SELECT
        *,
        CASE
            WHEN years_tenure < 0.5    THEN '0-6 months'
            WHEN years_tenure < 1.0    THEN '6-12 months'
            WHEN years_tenure < 2.0    THEN '1-2 years'
            WHEN years_tenure < 5.0    THEN '2-5 years'
            WHEN years_tenure < 10.0   THEN '5-10 years'
            ELSE                            '10+ years'
        END AS tenure_band,
        CASE
            WHEN years_tenure < 0.5    THEN 1
            WHEN years_tenure < 1.0    THEN 2
            WHEN years_tenure < 2.0    THEN 3
            WHEN years_tenure < 5.0    THEN 4
            WHEN years_tenure < 10.0   THEN 5
            ELSE                            6
        END AS tenure_order
    FROM engagement_data
)
SELECT
    tenure_band,
    tenure_order,
    COUNT(*)                                    AS headcount,
    ROUND(AVG(avg_q12_score), 3)                AS avg_q12_score,
    ROUND(AVG(absence_days), 1)                 AS avg_absence_days,
    ROUND(AVG(intent_to_stay::NUMERIC), 2)      AS avg_intent_to_stay,
    ROUND(
        SUM(CASE WHEN engagement_segment = 'Engaged' THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*),
        1
    )                                           AS engaged_pct
FROM tenure_bands
GROUP BY tenure_band, tenure_order
ORDER BY tenure_order;


-- ============================================================
-- QUERY 6: FLIGHT RISK PROFILE
-- Flags employees most likely to leave based on low engagement
-- and low intent to stay. Breakdown by department and segment
-- enables targeted retention action.
-- ============================================================

SELECT
    department,
    engagement_segment,
    job_level,
    COUNT(*)                                                AS headcount,
    SUM(flight_risk_flag)                                   AS flight_risk_count,
    ROUND(
        SUM(flight_risk_flag) * 100.0 / COUNT(*),
        1
    )                                                       AS flight_risk_pct,
    ROUND(AVG(avg_q12_score), 3)                            AS avg_q12_score,
    ROUND(AVG(intent_to_stay::NUMERIC), 2)                  AS avg_intent_to_stay
FROM engagement_data
GROUP BY department, engagement_segment, job_level
ORDER BY flight_risk_pct DESC NULLS LAST;


-- ============================================================
-- QUERY 7: INDIVIDUAL FLIGHT RISK ROSTER
-- Row-level list of employees flagged for retention risk.
-- Sorted by combined urgency: lowest Q12 + lowest intent to stay.
-- Used for drill-through and HR action planning.
-- ============================================================

SELECT
    employee_id,
    department,
    job_level,
    manager_id,
    years_tenure,
    engagement_segment,
    ROUND(avg_q12_score, 3)                     AS avg_q12_score,
    intent_to_stay,
    absence_days,
    performance_rating,
    enps_segment,
    ROUND(avg_q12_score + intent_to_stay, 2)    AS urgency_index
FROM engagement_data
WHERE flight_risk_flag = 1
ORDER BY urgency_index ASC;


-- ============================================================
-- QUERY 8: WEAKEST Q12 ITEMS ACROSS THE ORGANISATION
-- Identifies which of the 12 engagement dimensions score lowest overall.
-- Low-scoring items surface the most actionable intervention themes.
-- Gallup recommends focusing on the bottom 2-3 items per team.
-- ============================================================

SELECT item, item_label, ROUND(avg_score, 3) AS avg_score
FROM (
    VALUES
        ('q01', 'Expectations clear',          (SELECT AVG(q01) FROM engagement_data)),
        ('q02', 'Materials and equipment',      (SELECT AVG(q02) FROM engagement_data)),
        ('q03', 'Do what I do best',            (SELECT AVG(q03) FROM engagement_data)),
        ('q04', 'Recognition last 7 days',      (SELECT AVG(q04) FROM engagement_data)),
        ('q05', 'Someone cares about me',       (SELECT AVG(q05) FROM engagement_data)),
        ('q06', 'Development encouraged',       (SELECT AVG(q06) FROM engagement_data)),
        ('q07', 'Opinions count',               (SELECT AVG(q07) FROM engagement_data)),
        ('q08', 'Mission makes job important',  (SELECT AVG(q08) FROM engagement_data)),
        ('q09', 'Colleagues do quality work',   (SELECT AVG(q09) FROM engagement_data)),
        ('q10', 'Best friend at work',          (SELECT AVG(q10) FROM engagement_data)),
        ('q11', 'Progress discussed',           (SELECT AVG(q11) FROM engagement_data)),
        ('q12', 'Learn and grow opportunity',   (SELECT AVG(q12) FROM engagement_data))
) AS items(item, item_label, avg_score)
ORDER BY avg_score ASC;


-- ============================================================
-- QUERY 9: ENGAGEMENT VS. BUSINESS OUTCOMES CORRELATION
-- Validates that the engagement data connects to business metrics.
-- Gallup benchmarks for top-quartile vs. bottom-quartile teams:
--   Absenteeism: 81% lower | Productivity proxy: 23% higher
-- ============================================================

WITH quartiles AS (
    SELECT
        *,
        NTILE(4) OVER (ORDER BY avg_q12_score) AS engagement_quartile
    FROM engagement_data
)
SELECT
    engagement_quartile,
    COUNT(*)                                    AS headcount,
    ROUND(AVG(avg_q12_score), 3)                AS avg_q12_score,
    ROUND(AVG(absence_days), 1)                 AS avg_absence_days,
    ROUND(AVG(performance_rating::NUMERIC), 2)  AS avg_performance_rating,
    ROUND(AVG(intent_to_stay::NUMERIC), 2)      AS avg_intent_to_stay,
    SUM(flight_risk_flag)                       AS flight_risk_count,
    ROUND(
        SUM(flight_risk_flag) * 100.0 / COUNT(*),
        1
    )                                           AS flight_risk_pct
FROM quartiles
GROUP BY engagement_quartile
ORDER BY engagement_quartile;


-- ============================================================
-- QUERY 10: EXECUTIVE SCORECARD — SINGLE ROW SUMMARY
-- All headline metrics for the Power BI KPI page in one query.
-- ============================================================

WITH base AS (
    SELECT
        COUNT(*)                                                                            AS total_headcount,
        ROUND(AVG(avg_q12_score), 3)                                                       AS overall_avg_q12,
        ROUND(
            SUM(CASE WHEN engagement_segment = 'Engaged'             THEN 1 ELSE 0 END)
            * 100.0 / COUNT(*), 1
        )                                                                                   AS engaged_pct,
        ROUND(
            SUM(CASE WHEN engagement_segment = 'Not Engaged'          THEN 1 ELSE 0 END)
            * 100.0 / COUNT(*), 1
        )                                                                                   AS not_engaged_pct,
        ROUND(
            SUM(CASE WHEN engagement_segment = 'Actively Disengaged'  THEN 1 ELSE 0 END)
            * 100.0 / COUNT(*), 1
        )                                                                                   AS actively_disengaged_pct,
        SUM(flight_risk_flag)                                                               AS total_flight_risk,
        ROUND(SUM(flight_risk_flag) * 100.0 / COUNT(*), 1)                                 AS flight_risk_pct,
        ROUND(AVG(absence_days), 1)                                                        AS avg_absence_days,
        ROUND(AVG(absence_days) FILTER (WHERE engagement_segment = 'Engaged'), 1)          AS engaged_absence_days,
        ROUND(AVG(absence_days) FILTER (WHERE engagement_segment = 'Actively Disengaged'), 1) AS disengaged_absence_days,
        ROUND(AVG(intent_to_stay::NUMERIC), 2)                                             AS avg_intent_to_stay
    FROM engagement_data
)
SELECT
    total_headcount,
    overall_avg_q12,
    engaged_pct,
    not_engaged_pct,
    actively_disengaged_pct,
    total_flight_risk,
    flight_risk_pct,
    avg_absence_days,
    engaged_absence_days,
    disengaged_absence_days,
    ROUND(
        (disengaged_absence_days - engaged_absence_days)
        / NULLIF(disengaged_absence_days, 0) * 100,
        1
    )                                                               AS absence_reduction_if_engaged_pct,
    avg_intent_to_stay
FROM base;
